default:
  image: php:8.3

stages:
  - test
  - deploy

unit_test:
  stage: test
  script:
    - apt-get update -y && apt-get install -y git unzip curl libzip-dev libpng-dev libonig-dev libxml2-dev
    - docker-php-ext-install pdo pdo_mysql
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - vendor/bin/phpunit

deploy_production:
  stage: deploy
  script:
    - apt-get update -y && apt-get install -y git unzip curl openssh-client
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer global require laravel/envoy
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
    - chmod 600 /tmp/deploy_key
    - ssh-add /tmp/deploy_key
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ~/.composer/vendor/bin/envoy run deploy --commit="$CI_COMMIT_SHA"
  environment:
    name: production
    url: http://172.25.46.154
  when: manual
  only:
    - main
